spring.application.name=ollama
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %blue([%thread]) %yellow(%logger{15}) - %msg%n
#spring.ai.model.chat=ollama
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.chat.model=llama3.2:latest
